# Generated by Django 6.1 on 2026-09-20 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='title',
            field=models.CharField(default=('messages__sender', 'messages__likes'), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doubt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='doubts', to='skills.skilltag'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doubtmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='doubt_messages/'),
        ),
        migrations.AddField(
            model_name='doubtmessage',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DoubtLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='doubts.doubt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('doubt', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DoubtMessageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='doubts.doubtmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt_message_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
