# Generated by Django 6.1 on 2026-09-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0002_doubt_attachment_doubt_title_doubt_topic_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='skills.skilltag'),
        ),
    ]
