# Generated by Django 6.1 on 2026-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0003_alter_doubt_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtmessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
