# Generated by Django 6.1 on 2026-09-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.AddField(
            model_name='program',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
