# Generated by Django 6.1 on 2026-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_program_duration_program_duration_weeks'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('course', 'year', 'branch', 'section', 'organization', 'current_program'), name='unique_class_group'),
        ),
    ]
