# Generated by Django 6.1 on 2026-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classgroup_unique_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='program_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
