# Generated by Django 6.1 on 2026-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/lecture/'),
        ),
    ]
