# Generated by Django 6.1 on 2026-09-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classgroup_program_started_at'),
        ('lectures', '0002_lecture_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['day_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='lecture',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='classes.program'),
            preserve_default=False,
        ),
    ]
